Wwwision:
  ImportService:
    presets:
      'test':
        syncOnly: false
        source:
          className: 'Wwwision\ImportService\DataSource\DbalSource'
          options:
            backendOptions:
              dbname: test
            table: 'source'
          fixture:
            file: 'resource://some/file'
          postProcessor: 'Wwwision\Webkatalog\Service\ImportService\PapiProcessors::processEducationalAreas'
        target:
          className: 'Wwwision\ImportService\DataTarget\DbalTarget'
          options:
            table: 'target'
            idColumn: 'slug'
            versionColumn: 'version'
        mapping:
          'slug': 'id'
          'givenname': '${record.foo}'
          'familyname': 'lastname'
          'version': 'revision'
